# Generated by Django 6.0.3 on 2026-03-08 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to_collection_raw', models.TextField(blank=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('genres_raw', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True, max_length=500)),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('original_language_code', models.CharField(blank=True, max_length=10)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('production_companies_raw', models.TextField(blank=True)),
                ('production_countries_raw', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('spoken_languages_raw', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movieranker.genre')),
                ('original_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_language_movies', to='movieranker.language')),
                ('production_companies', models.ManyToManyField(blank=True, related_name='movies', to='movieranker.company')),
                ('production_countries', models.ManyToManyField(blank=True, related_name='movies', to='movieranker.country')),
                ('spoken_languages', models.ManyToManyField(blank=True, related_name='spoken_language_movies', to='movieranker.language')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ['-release_date', '-vote_average'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField(db_index=True, unique=True)),
                ('imdbId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tmdbId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='movieranker.movie')),
            ],
            options={
                'verbose_name': 'link (MovieLens - IMDb - TMDb)',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(db_index=True)),
                ('movieId', models.IntegerField(db_index=True)),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='movieranker.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date', 'vote_average'], name='movieranker_release_6a94ec_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movieranker_title_9e0965_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-popularity'], name='movieranker_popular_c8f6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['movieId'], name='movieranker_movieId_5bdb57_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['imdbId'], name='movieranker_imdbId_55c87d_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['tmdbId'], name='movieranker_tmdbId_145857_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'movieId'], name='movieranker_user_id_2e3255_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-timestamp'], name='movieranker_timesta_4ad706_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'movieId', 'timestamp'), name='uniq_user_ml_movie_ts'),
        ),
    ]
