# Generated by Django 6.0.3 on 2026-03-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieranker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTOR', 'Actor'), ('CREW', 'Crew')], max_length=10)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('character', models.CharField(blank=True, max_length=200)),
                ('cast_order', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movieranker.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movieranker.person')),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'job'], name='movieranker_role_c559c8_idx'), models.Index(fields=['cast_order'], name='movieranker_cast_or_446d4a_idx')],
                'constraints': [models.UniqueConstraint(fields=('movie', 'person', 'role', 'job', 'character'), name='uniq_movie_person_role_job_character')],
            },
        ),
    ]
